"""Add time field

Revision ID: 501a412bb7e6
Revises: 45212a14329c
Create Date: 2025-02-19 20:06:30.645567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501a412bb7e6'
down_revision = '45212a14329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'time')
    # ### end Alembic commands ###
