"""Add new field is active Scene

Revision ID: 836dbb2e4017
Revises: 2ba29f5cf413
Create Date: 2025-06-13 21:58:08.738114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836dbb2e4017'
down_revision = '2ba29f5cf413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('devices', 'css',
    #            existing_type=sa.VARCHAR(length=20000),
    #            type_=sa.String(length=2000),
    #            existing_nullable=False)
    # op.alter_column('devices', 'html',
    #            existing_type=sa.VARCHAR(length=20000),
    #            type_=sa.String(length=2000),
    #            existing_nullable=False)
    # op.alter_column('meta_button', 'css',
    #            existing_type=sa.VARCHAR(length=20000),
    #            type_=sa.String(length=2000),
    #            existing_nullable=False)
    # op.alter_column('meta_button', 'html',
    #            existing_type=sa.VARCHAR(length=20000),
    #            type_=sa.String(length=2000),
    #            existing_nullable=False)
    op.add_column('scenes', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('scenes', 'active')
    # op.alter_column('meta_button', 'html',
    #            existing_type=sa.String(length=2000),
    #            type_=sa.VARCHAR(length=20000),
    #            existing_nullable=False)
    # op.alter_column('meta_button', 'css',
    #            existing_type=sa.String(length=2000),
    #            type_=sa.VARCHAR(length=20000),
    #            existing_nullable=False)
    # op.alter_column('devices', 'html',
    #            existing_type=sa.String(length=2000),
    #            type_=sa.VARCHAR(length=20000),
    #            existing_nullable=False)
    # op.alter_column('devices', 'css',
    #            existing_type=sa.String(length=2000),
    #            type_=sa.VARCHAR(length=20000),
    #            existing_nullable=False)
    # ### end Alembic commands ###
    pass
